// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:boo_mondai/core/hive/adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(CachedMediaAdapter());
    registerAdapter(CardAdapter());
    registerAdapter(CardTemplateDirectionAdapter());
    registerAdapter(CardTemplateTagAdapter());
    registerAdapter(CardTemplateTypeAdapter());
    registerAdapter(CasingTypeAdapter());
    registerAdapter(ContentAdapter());
    registerAdapter(DeckAdapter());
    registerAdapter(DeckListingAdapter());
    registerAdapter(DeckTagAdapter());
    registerAdapter(FillInTheBlankSegmentAdapter());
    registerAdapter(FillInTheBlanksTemplateAdapter());
    registerAdapter(FlashcardTemplateAdapter());
    registerAdapter(FsrsCardAdapter());
    registerAdapter(FsrsReviewLogAdapter());
    registerAdapter(IdentificationAnswerAdapter());
    registerAdapter(IdentificationTemplateAdapter());
    registerAdapter(MatchMadnessPairAdapter());
    registerAdapter(MatchMadnessTemplateAdapter());
    registerAdapter(MultipleChoiceOptionAdapter());
    registerAdapter(MultipleChoiceTemplateAdapter());
    registerAdapter(ProfileAdapter());
    registerAdapter(ProgressCheckpointAdapter());
    registerAdapter(ProgressCheckpointStatusAdapter());
    registerAdapter(ProgressCheckpointTypeAdapter());
    registerAdapter(RatingAdapter());
    registerAdapter(ReviewLogAdapter());
    registerAdapter(ReviewSessionAdapter());
    registerAdapter(StateAdapter());
    registerAdapter(StreakAdapter());
    registerAdapter(StudyCardAdapter());
    registerAdapter(StudyRatingAdapter());
    registerAdapter(StudySessionAnswerAdapter());
    registerAdapter(StudySessionCardStepAdapter());
    registerAdapter(StudySessionMessageStepAdapter());
    registerAdapter(StudySessionSnapshotAdapter());
    registerAdapter(SurveyResponseAdapter());
    registerAdapter(SyncClientAdapter());
    registerAdapter(SyncDeletionAdapter());
    registerAdapter(TagAdapter());
    registerAdapter(UserAdapter());
    registerAdapter(UserSettingsAdapter());
    registerAdapter(UserStudyCardTagAdapter());
    registerAdapter(VisibilityStateAdapter());
    registerAdapter(WordScrambleTemplateAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(CachedMediaAdapter());
    registerAdapter(CardAdapter());
    registerAdapter(CardTemplateDirectionAdapter());
    registerAdapter(CardTemplateTagAdapter());
    registerAdapter(CardTemplateTypeAdapter());
    registerAdapter(CasingTypeAdapter());
    registerAdapter(ContentAdapter());
    registerAdapter(DeckAdapter());
    registerAdapter(DeckListingAdapter());
    registerAdapter(DeckTagAdapter());
    registerAdapter(FillInTheBlankSegmentAdapter());
    registerAdapter(FillInTheBlanksTemplateAdapter());
    registerAdapter(FlashcardTemplateAdapter());
    registerAdapter(FsrsCardAdapter());
    registerAdapter(FsrsReviewLogAdapter());
    registerAdapter(IdentificationAnswerAdapter());
    registerAdapter(IdentificationTemplateAdapter());
    registerAdapter(MatchMadnessPairAdapter());
    registerAdapter(MatchMadnessTemplateAdapter());
    registerAdapter(MultipleChoiceOptionAdapter());
    registerAdapter(MultipleChoiceTemplateAdapter());
    registerAdapter(ProfileAdapter());
    registerAdapter(ProgressCheckpointAdapter());
    registerAdapter(ProgressCheckpointStatusAdapter());
    registerAdapter(ProgressCheckpointTypeAdapter());
    registerAdapter(RatingAdapter());
    registerAdapter(ReviewLogAdapter());
    registerAdapter(ReviewSessionAdapter());
    registerAdapter(StateAdapter());
    registerAdapter(StreakAdapter());
    registerAdapter(StudyCardAdapter());
    registerAdapter(StudyRatingAdapter());
    registerAdapter(StudySessionAnswerAdapter());
    registerAdapter(StudySessionCardStepAdapter());
    registerAdapter(StudySessionMessageStepAdapter());
    registerAdapter(StudySessionSnapshotAdapter());
    registerAdapter(SurveyResponseAdapter());
    registerAdapter(SyncClientAdapter());
    registerAdapter(SyncDeletionAdapter());
    registerAdapter(TagAdapter());
    registerAdapter(UserAdapter());
    registerAdapter(UserSettingsAdapter());
    registerAdapter(UserStudyCardTagAdapter());
    registerAdapter(VisibilityStateAdapter());
    registerAdapter(WordScrambleTemplateAdapter());
  }
}
