// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:boo_mondai/core/hive/adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AttachmentTypeAdapter());
    registerAdapter(CachedProfileAdapter());
    registerAdapter(CardAdapter());
    registerAdapter(CardLinkAttachmentAdapter());
    registerAdapter(CardMediaAttachmentAdapter());
    registerAdapter(CardTemplateTagAdapter());
    registerAdapter(CardTypeAdapter());
    registerAdapter(DeckAdapter());
    registerAdapter(DeckListingAdapter());
    registerAdapter(DeckTagAdapter());
    registerAdapter(DownloadCheckpointAdapter());
    registerAdapter(DownloadCheckpointStatusAdapter());
    registerAdapter(DrillAnswerAdapter());
    registerAdapter(DrillSessionAdapter());
    registerAdapter(FillInTheBlankSegmentAdapter());
    registerAdapter(FillInTheBlanksTemplateAdapter());
    registerAdapter(FlashcardTemplateAdapter());
    registerAdapter(FsrsCardAdapter());
    registerAdapter(FsrsReviewLogAdapter());
    registerAdapter(IdentificationTemplateAdapter());
    registerAdapter(ImportExportBackupAdapter());
    registerAdapter(LocalImageCacheEntryAdapter());
    registerAdapter(MatchMadnessPairAdapter());
    registerAdapter(MatchMadnessTemplateAdapter());
    registerAdapter(MultipleChoiceOptionAdapter());
    registerAdapter(MultipleChoiceTemplateAdapter());
    registerAdapter(ProfileAdapter());
    registerAdapter(QuestionTypeAdapter());
    registerAdapter(RatingAdapter());
    registerAdapter(ReviewLogAdapter());
    registerAdapter(ReviewSessionAdapter());
    registerAdapter(StateAdapter());
    registerAdapter(StreakAdapter());
    registerAdapter(StudyCardAdapter());
    registerAdapter(StudyRatingAdapter());
    registerAdapter(TagAdapter());
    registerAdapter(UserAdapter());
    registerAdapter(UserSettingsAdapter());
    registerAdapter(UserStudyCardTagAdapter());
    registerAdapter(VisibilityStateAdapter());
    registerAdapter(WordScrambleTemplateAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AttachmentTypeAdapter());
    registerAdapter(CachedProfileAdapter());
    registerAdapter(CardAdapter());
    registerAdapter(CardLinkAttachmentAdapter());
    registerAdapter(CardMediaAttachmentAdapter());
    registerAdapter(CardTemplateTagAdapter());
    registerAdapter(CardTypeAdapter());
    registerAdapter(DeckAdapter());
    registerAdapter(DeckListingAdapter());
    registerAdapter(DeckTagAdapter());
    registerAdapter(DownloadCheckpointAdapter());
    registerAdapter(DownloadCheckpointStatusAdapter());
    registerAdapter(DrillAnswerAdapter());
    registerAdapter(DrillSessionAdapter());
    registerAdapter(FillInTheBlankSegmentAdapter());
    registerAdapter(FillInTheBlanksTemplateAdapter());
    registerAdapter(FlashcardTemplateAdapter());
    registerAdapter(FsrsCardAdapter());
    registerAdapter(FsrsReviewLogAdapter());
    registerAdapter(IdentificationTemplateAdapter());
    registerAdapter(ImportExportBackupAdapter());
    registerAdapter(LocalImageCacheEntryAdapter());
    registerAdapter(MatchMadnessPairAdapter());
    registerAdapter(MatchMadnessTemplateAdapter());
    registerAdapter(MultipleChoiceOptionAdapter());
    registerAdapter(MultipleChoiceTemplateAdapter());
    registerAdapter(ProfileAdapter());
    registerAdapter(QuestionTypeAdapter());
    registerAdapter(RatingAdapter());
    registerAdapter(ReviewLogAdapter());
    registerAdapter(ReviewSessionAdapter());
    registerAdapter(StateAdapter());
    registerAdapter(StreakAdapter());
    registerAdapter(StudyCardAdapter());
    registerAdapter(StudyRatingAdapter());
    registerAdapter(TagAdapter());
    registerAdapter(UserAdapter());
    registerAdapter(UserSettingsAdapter());
    registerAdapter(UserStudyCardTagAdapter());
    registerAdapter(VisibilityStateAdapter());
    registerAdapter(WordScrambleTemplateAdapter());
  }
}
