// Mocks generated by Mockito 5.4.6 from annotations
// in boo_mondai/test/helpers/mock_fsrs_service.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:boo_mondai/models/fsrs_card_state.dart' as _i3;
import 'package:boo_mondai/services/fsrs_service.dart' as _i4;
import 'package:fsrs/fsrs.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCard_0 extends _i1.SmartFake implements _i2.Card {
  _FakeCard_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeReviewLog_1 extends _i1.SmartFake implements _i2.ReviewLog {
  _FakeReviewLog_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFsrsCardState_2 extends _i1.SmartFake implements _i3.FsrsCardState {
  _FakeFsrsCardState_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [FsrsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFsrsService extends _i1.Mock implements _i4.FsrsService {
  MockFsrsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Card createNewCard() =>
      (super.noSuchMethod(
            Invocation.method(#createNewCard, []),
            returnValue: _FakeCard_0(
              this,
              Invocation.method(#createNewCard, []),
            ),
          )
          as _i2.Card);

  @override
  ({_i2.Card card, _i2.ReviewLog log}) scheduleCard(
    _i2.Card? card,
    _i2.Rating? rating,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#scheduleCard, [card, rating]),
            returnValue: (
              card: _FakeCard_0(
                this,
                Invocation.method(#scheduleCard, [card, rating]),
              ),
              log: _FakeReviewLog_1(
                this,
                Invocation.method(#scheduleCard, [card, rating]),
              ),
            ),
          )
          as ({_i2.Card card, _i2.ReviewLog log}));

  @override
  _i3.FsrsCardState reviewCard(_i3.FsrsCardState? state, int? ratingValue) =>
      (super.noSuchMethod(
            Invocation.method(#reviewCard, [state, ratingValue]),
            returnValue: _FakeFsrsCardState_2(
              this,
              Invocation.method(#reviewCard, [state, ratingValue]),
            ),
          )
          as _i3.FsrsCardState);

  @override
  _i3.FsrsCardState enrollCard(
    String? userId,
    String? cardId,
    int? ratingValue,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#enrollCard, [userId, cardId, ratingValue]),
            returnValue: _FakeFsrsCardState_2(
              this,
              Invocation.method(#enrollCard, [userId, cardId, ratingValue]),
            ),
          )
          as _i3.FsrsCardState);
}
