// Mocks generated by Mockito 5.4.6 from annotations
// in boo_mondai/test/helpers/mock_hive_service.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:boo_mondai/models/deck.dart' as _i5;
import 'package:boo_mondai/models/deck_card.dart' as _i6;
import 'package:boo_mondai/models/fsrs_card_state.dart' as _i7;
import 'package:boo_mondai/models/review_log_entry.dart' as _i8;
import 'package:boo_mondai/models/streak.dart' as _i9;
import 'package:boo_mondai/models/user_profile.dart' as _i4;
import 'package:boo_mondai/services/hive_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [HiveService].
///
/// See the documentation for Mockito's code generation for more information.
class MockHiveService extends _i1.Mock implements _i2.HiveService {
  MockHiveService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> init() =>
      (super.noSuchMethod(
            Invocation.method(#init, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> saveProfile(_i4.UserProfile? profile) =>
      (super.noSuchMethod(
            Invocation.method(#saveProfile, [profile]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> saveDecks(List<_i5.Deck>? decks) =>
      (super.noSuchMethod(
            Invocation.method(#saveDecks, [decks]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  List<_i5.Deck> getDecks() =>
      (super.noSuchMethod(
            Invocation.method(#getDecks, []),
            returnValue: <_i5.Deck>[],
          )
          as List<_i5.Deck>);

  @override
  _i3.Future<void> saveCards(String? deckId, List<_i6.DeckCard>? cards) =>
      (super.noSuchMethod(
            Invocation.method(#saveCards, [deckId, cards]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  List<_i6.DeckCard> getCards(String? deckId) =>
      (super.noSuchMethod(
            Invocation.method(#getCards, [deckId]),
            returnValue: <_i6.DeckCard>[],
          )
          as List<_i6.DeckCard>);

  @override
  _i3.Future<void> saveFsrsCard(_i7.FsrsCardState? card) =>
      (super.noSuchMethod(
            Invocation.method(#saveFsrsCard, [card]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i7.FsrsCardState? getFsrsCard(String? compositeKey) =>
      (super.noSuchMethod(Invocation.method(#getFsrsCard, [compositeKey]))
          as _i7.FsrsCardState?);

  @override
  List<_i7.FsrsCardState> getDueCards(String? userId, DateTime? now) =>
      (super.noSuchMethod(
            Invocation.method(#getDueCards, [userId, now]),
            returnValue: <_i7.FsrsCardState>[],
          )
          as List<_i7.FsrsCardState>);

  @override
  List<_i7.FsrsCardState> getAllFsrsCards(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getAllFsrsCards, [userId]),
            returnValue: <_i7.FsrsCardState>[],
          )
          as List<_i7.FsrsCardState>);

  @override
  _i3.Future<void> saveReviewLog(_i8.ReviewLogEntry? log) =>
      (super.noSuchMethod(
            Invocation.method(#saveReviewLog, [log]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> saveStreak(_i9.Streak? streak) =>
      (super.noSuchMethod(
            Invocation.method(#saveStreak, [streak]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i9.Streak? getStreak(String? userId) =>
      (super.noSuchMethod(Invocation.method(#getStreak, [userId]))
          as _i9.Streak?);

  @override
  int getNotificationHour() =>
      (super.noSuchMethod(
            Invocation.method(#getNotificationHour, []),
            returnValue: 0,
          )
          as int);

  @override
  _i3.Future<void> setNotificationHour(int? hour) =>
      (super.noSuchMethod(
            Invocation.method(#setNotificationHour, [hour]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> clearAll() =>
      (super.noSuchMethod(
            Invocation.method(#clearAll, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
