// Mocks generated by Mockito 5.4.6 from annotations
// in boo_mondai/test/helpers/mock_supabase_service.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:typed_data' as _i5;

import 'package:boo_mondai/services/supabase_service.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:supabase_flutter/supabase_flutter.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAuthResponse_0 extends _i1.SmartFake implements _i2.AuthResponse {
  _FakeAuthResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SupabaseService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSupabaseService extends _i1.Mock implements _i3.SupabaseService {
  MockSupabaseService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.AuthResponse> signIn(String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#signIn, [email, password]),
            returnValue: _i4.Future<_i2.AuthResponse>.value(
              _FakeAuthResponse_0(
                this,
                Invocation.method(#signIn, [email, password]),
              ),
            ),
          )
          as _i4.Future<_i2.AuthResponse>);

  @override
  _i4.Future<_i2.AuthResponse> signUp(String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#signUp, [email, password]),
            returnValue: _i4.Future<_i2.AuthResponse>.value(
              _FakeAuthResponse_0(
                this,
                Invocation.method(#signUp, [email, password]),
              ),
            ),
          )
          as _i4.Future<_i2.AuthResponse>);

  @override
  _i4.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<Map<String, dynamic>?> getProfile(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getProfile, [userId]),
            returnValue: _i4.Future<Map<String, dynamic>?>.value(),
          )
          as _i4.Future<Map<String, dynamic>?>);

  @override
  _i4.Future<void> upsertProfile(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
            Invocation.method(#upsertProfile, [data]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<Map<String, dynamic>>> fetchDecks({
    bool? publicOnly = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchDecks, [], {#publicOnly: publicOnly}),
            returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<List<Map<String, dynamic>>> fetchUserDecks(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchUserDecks, [userId]),
            returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<Map<String, dynamic>> insertDeck(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
            Invocation.method(#insertDeck, [data]),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<void> updateDeck(String? id, Map<String, dynamic>? data) =>
      (super.noSuchMethod(
            Invocation.method(#updateDeck, [id, data]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteDeck(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteDeck, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<Map<String, dynamic>>> fetchCards(String? deckId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchCards, [deckId]),
            returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<Map<String, dynamic>> insertCard(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
            Invocation.method(#insertCard, [data]),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<void> updateCard(String? id, Map<String, dynamic>? data) =>
      (super.noSuchMethod(
            Invocation.method(#updateCard, [id, data]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteCard(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteCard, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<Map<String, dynamic>> insertQuizSession(
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#insertQuizSession, [data]),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<void> updateQuizSession(String? id, Map<String, dynamic>? data) =>
      (super.noSuchMethod(
            Invocation.method(#updateQuizSession, [id, data]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> insertQuizAnswer(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
            Invocation.method(#insertQuizAnswer, [data]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> upsertFsrsCard(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
            Invocation.method(#upsertFsrsCard, [data]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> insertReviewLog(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
            Invocation.method(#insertReviewLog, [data]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<Map<String, dynamic>>> fetchLeaderboard({
    String? targetLanguage,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchLeaderboard, [], {
              #targetLanguage: targetLanguage,
            }),
            returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<void> upsertStreak(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
            Invocation.method(#upsertStreak, [data]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<Map<String, dynamic>?> fetchStreak(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchStreak, [userId]),
            returnValue: _i4.Future<Map<String, dynamic>?>.value(),
          )
          as _i4.Future<Map<String, dynamic>?>);

  @override
  _i4.Future<List<Map<String, dynamic>>> fetchResearchCodes({
    String? createdBy,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchResearchCodes, [], {#createdBy: createdBy}),
            returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<Map<String, dynamic>> insertResearchCode(
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#insertResearchCode, [data]),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> redeemResearchCode(
    String? code,
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#redeemResearchCode, [code, userId]),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<void> insertSurveyResponse(
    String? table,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#insertSurveyResponse, [table, data]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> insertVocabularyTest(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
            Invocation.method(#insertVocabularyTest, [data]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<Map<String, List<Map<String, dynamic>>>> fetchAllResearchData() =>
      (super.noSuchMethod(
            Invocation.method(#fetchAllResearchData, []),
            returnValue:
                _i4.Future<Map<String, List<Map<String, dynamic>>>>.value(
                  <String, List<Map<String, dynamic>>>{},
                ),
          )
          as _i4.Future<Map<String, List<Map<String, dynamic>>>>);

  @override
  _i4.Future<void> insertResearchUser(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
            Invocation.method(#insertResearchUser, [data]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<String> uploadImage(
    String? bucket,
    String? path,
    _i5.Uint8List? bytes,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#uploadImage, [bucket, path, bytes]),
            returnValue: _i4.Future<String>.value(
              _i6.dummyValue<String>(
                this,
                Invocation.method(#uploadImage, [bucket, path, bytes]),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<void> deleteImage(String? bucket, String? path) =>
      (super.noSuchMethod(
            Invocation.method(#deleteImage, [bucket, path]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
