// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:boo_mondai/hive/adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(CachedProfileAdapter());
    registerAdapter(CardAdapter());
    registerAdapter(CardTypeAdapter());
    registerAdapter(DeckAdapter());
    registerAdapter(DrillAnswerAdapter());
    registerAdapter(DrillSessionAdapter());
    registerAdapter(FillInTheBlankSegmentAdapter());
    registerAdapter(FillInTheBlanksTemplateAdapter());
    registerAdapter(FlashcardTemplateAdapter());
    registerAdapter(FsrsCardAdapter());
    registerAdapter(FsrsReviewLogAdapter());
    registerAdapter(IdentificationTemplateAdapter());
    registerAdapter(MatchMadnessPairAdapter());
    registerAdapter(MatchMadnessTemplateAdapter());
    registerAdapter(MultipleChoiceOptionAdapter());
    registerAdapter(MultipleChoiceTemplateAdapter());
    registerAdapter(ProfileAdapter());
    registerAdapter(QuestionTypeAdapter());
    registerAdapter(RatingAdapter());
    registerAdapter(ReviewCardAdapter());
    registerAdapter(ReviewLogAdapter());
    registerAdapter(ReviewSessionAdapter());
    registerAdapter(StateAdapter());
    registerAdapter(StreakAdapter());
    registerAdapter(StudyRatingAdapter());
    registerAdapter(UserAdapter());
    registerAdapter(WordScrambleTemplateAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(CachedProfileAdapter());
    registerAdapter(CardAdapter());
    registerAdapter(CardTypeAdapter());
    registerAdapter(DeckAdapter());
    registerAdapter(DrillAnswerAdapter());
    registerAdapter(DrillSessionAdapter());
    registerAdapter(FillInTheBlankSegmentAdapter());
    registerAdapter(FillInTheBlanksTemplateAdapter());
    registerAdapter(FlashcardTemplateAdapter());
    registerAdapter(FsrsCardAdapter());
    registerAdapter(FsrsReviewLogAdapter());
    registerAdapter(IdentificationTemplateAdapter());
    registerAdapter(MatchMadnessPairAdapter());
    registerAdapter(MatchMadnessTemplateAdapter());
    registerAdapter(MultipleChoiceOptionAdapter());
    registerAdapter(MultipleChoiceTemplateAdapter());
    registerAdapter(ProfileAdapter());
    registerAdapter(QuestionTypeAdapter());
    registerAdapter(RatingAdapter());
    registerAdapter(ReviewCardAdapter());
    registerAdapter(ReviewLogAdapter());
    registerAdapter(ReviewSessionAdapter());
    registerAdapter(StateAdapter());
    registerAdapter(StreakAdapter());
    registerAdapter(StudyRatingAdapter());
    registerAdapter(UserAdapter());
    registerAdapter(WordScrambleTemplateAdapter());
  }
}
