// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:boo_mondai/hive/adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(CachedProfileAdapter());
    registerAdapter(CardAdapter());
    registerAdapter(CardTypeAdapter());
    registerAdapter(DeckAdapter());
    registerAdapter(DeckCardAdapter());
    registerAdapter(FillInTheBlankSegmentAdapter());
    registerAdapter(MatchMadnessPairAdapter());
    registerAdapter(MultipleChoiceOptionAdapter());
    registerAdapter(NoteAdapter());
    registerAdapter(QuestionTypeAdapter());
    registerAdapter(ReviewLogAdapter());
    registerAdapter(StreakAdapter());
    registerAdapter(UserProfileAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(CachedProfileAdapter());
    registerAdapter(CardAdapter());
    registerAdapter(CardTypeAdapter());
    registerAdapter(DeckAdapter());
    registerAdapter(DeckCardAdapter());
    registerAdapter(FillInTheBlankSegmentAdapter());
    registerAdapter(MatchMadnessPairAdapter());
    registerAdapter(MultipleChoiceOptionAdapter());
    registerAdapter(NoteAdapter());
    registerAdapter(QuestionTypeAdapter());
    registerAdapter(ReviewLogAdapter());
    registerAdapter(StreakAdapter());
    registerAdapter(UserProfileAdapter());
  }
}
