// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:boo_mondai/hive/adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(DeckAdapter());
    registerAdapter(DeckCardAdapter());
    registerAdapter(FsrsCardStateAdapter());
    registerAdapter(ReviewLogEntryAdapter());
    registerAdapter(StreakAdapter());
    registerAdapter(UserProfileAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(DeckAdapter());
    registerAdapter(DeckCardAdapter());
    registerAdapter(FsrsCardStateAdapter());
    registerAdapter(ReviewLogEntryAdapter());
    registerAdapter(StreakAdapter());
    registerAdapter(UserProfileAdapter());
  }
}
