import 'package:boo_mondai/lib.barrel.dart'
    show
        AppTokens,
        fontFamily,
        radiusContainerLarge,
        radius2xl,
        radius3xl,
        surfaceShadowOffset,
        modalShadowOffset,
        borderWidthDefault,
        spacePanelPadding,
        spacePanelGapSm,
        spacePanelGapLg,
        spacePanelGapMd,
        textSizeHeader,
        textSizeLabelLarge,
        textSizeLabel,
        textSizeLabelSmall,
        textSizeBodyLarge,
        textSizeCardFront,
        textSizeCardBackFront,
        textSizeCardBackContent,
        fontWeightTextBody,
        fontWeightTextStrong,
        fontWeightTextHeavy,
        lineHeightTextBody,
        lineHeightTextTitle,
        lineHeightTextDisplay,
        lineHeightFieldDisplay,
        lineHeightTactile,
        letterSpacingTextEyebrow,
        sizeIconMd,
        sizeIconLg,
        colorTransparent,
        colorTextOnBrand,
        cardAspectRatio,
        buildAppThemeData;
import 'package:flutter/material.dart' show Color, Brightness;
import 'package:theme_variants/theme_variants.dart'
    show ThemeVariant, ThemeVariantBrightness;

final AppTokens defaultDark = AppTokens(
  name: 'BooMondai Dark',
  fontFamily: fontFamily,
  primary: Color(0xff6366f1),
  primaryDim: Color(0xff3f498a),
  primaryBright: Color(0xff3730a3),
  primarySoft: Color(0xff312e81),
  streak: Color(0xfffb923c),
  streakDim: Color(0xffea580c),
  backgroundPage: Color(0xff0b1020),
  backgroundSurface: Color(0xff111827),
  borderNeutralSubtle: Color(0xff374151),
  actionSuccess: Color(0xff4ade80),
  actionSuccessBackground: Color(0xff052e16),
  actionSuccessBorder: Color(0xff14532d),
  actionError: Color(0xfff87171),
  actionErrorBackground: Color(0xff450a0a),
  actionErrorBorder: Color(0xff7f1d1d),
  textPrimary: Color(0xfff3f4f6),
  textSecondary: Color(0xffd1d5db),
  textMuted: Color(0xff9ca3af),
  softGray: Color(0xff1f2937),
  greenSoft: Color(0xff052e16),
  ratingAgainBackground: Color(0xff450a0a),
  ratingAgainText: Color(0xffff8a80),
  ratingAgainBorder: Color(0xff7f1d1d),
  ratingAgainHoverBackground: Color(0xff5f1414),
  ratingHardBackground: Color(0xff431407),
  ratingHardText: Color(0xffffb74d),
  ratingHardBorder: Color(0xff7c2d12),
  ratingHardHoverBackground: Color(0xff5a1d0a),
  ratingGoodBackground: Color(0xff052e16),
  ratingGoodText: Color(0xff81c784),
  ratingGoodBorder: Color(0xff14532d),
  ratingGoodHoverBackground: Color(0xff0b3d1f),
  ratingEasyBackground: Color(0xff082f49),
  ratingEasyText: Color(0xff64b5f6),
  ratingEasyBorder: Color(0xff075985),
  ratingEasyHoverBackground: Color(0xff0c4a6e),
  radiusContainerLarge: radiusContainerLarge,
  radius2xl: radius2xl,
  radius3xl: radius3xl,
  surfaceShadowOffset: surfaceShadowOffset,
  modalShadowOffset: modalShadowOffset,
  borderWidthDefault: borderWidthDefault,
  spacePanelPadding: spacePanelPadding,
  spacePanelPaddingSm: spacePanelGapSm,
  spacePanelGapLg: spacePanelGapLg,
  spacePanelGapMd: spacePanelGapMd,
  spacePanelGapSm: spacePanelGapSm,
  textSizeHeader: textSizeHeader,
  textSizeLabelLarge: textSizeLabelLarge,
  textSizeLabel: textSizeLabel,
  textSizeLabelSmall: textSizeLabelSmall,
  textSizeBodyLarge: textSizeBodyLarge,
  textSizeCardFront: textSizeCardFront,
  textSizeCardBackFront: textSizeCardBackFront,
  textSizeCardBackContent: textSizeCardBackContent,
  fontWeightTextBody: fontWeightTextBody,
  fontWeightTextStrong: fontWeightTextStrong,
  fontWeightTextHeavy: fontWeightTextHeavy,
  lineHeightTextBody: lineHeightTextBody,
  lineHeightTextTitle: lineHeightTextTitle,
  lineHeightTextDisplay: lineHeightTextDisplay,
  lineHeightFieldDisplay: lineHeightFieldDisplay,
  lineHeightTactile: lineHeightTactile,
  letterSpacingTextEyebrow: letterSpacingTextEyebrow,
  sizeIconMd: sizeIconMd,
  sizeIconLg: sizeIconLg,
  colorTransparent: colorTransparent,
  colorTextOnBrand: colorTextOnBrand,
  cardAspectRatio: cardAspectRatio,
);

final booMondaiDark = ThemeVariant<AppTokens>(
  themePresetId: 'boomondai',
  brightness: ThemeVariantBrightness.dark,
  themeData: buildAppThemeData(defaultDark, Brightness.dark),
  tokens: defaultDark,
);
