import 'package:boo_mondai/core/theme/app_tokens.shared.dart';
import 'package:boo_mondai/lib.barrel.dart'
    show
        AppTokens,
        fontFamily,
        radiusSurface,
        radiusSurfaceLg,
        radiusSurfaceSm,
        buttonShadowOffset,
        modalShadowOffset,
        borderWidthDefault,
        spaceScaffoldPadding,
        spaceLayoutPadding,
        spaceLayoutGapSm,
        spaceLayoutGapLg,
        spaceLayoutGapMd,
        spaceScaffoldMaxWidth,
        textSizeHeader,
        textSizeLabelLarge,
        textSizeLabel,
        textSizeLabelSmall,
        textSizeBodyLarge,
        studyCardTextSizeFront,
        studyCardTextSizeBack,
        studyCardTextSizeBackContent,
        fontWeightTextBody,
        fontWeightTextStrong,
        fontWeightTextHeavy,
        lineHeightTextBody,
        lineHeightTextTitle,
        lineHeightTextDisplay,
        lineHeightFieldDisplay,
        lineHeightButton,
        letterSpacingTextEyebrow,
        sizeIconMd,
        sizeIconLg,
        colorTransparent,
        colorTextOnBrand,
        studyCardAspectRatio,
        studyCardWidth,
        studyCardRadius,
        buildAppThemeData;
import 'package:flutter/material.dart' show Color, Brightness;
import 'package:theme_variants/theme_variants.dart'
    show ThemeVariant, ThemeVariantBrightness;

final AppTokens defaultDark = AppTokens(
  name: 'BooMondai Dark',
  fontFamily: fontFamily,
  colorPrimaryBright: Color(0xff3730a3),
  colorPrimaryDim: Color(0xff3f498a),
  colorPrimarySoft: Color(0xff312e81),
  colorStreak: Color(0xfffb923c),
  colorStreakDim: Color(0xffea580c),
  colorPageBackground: Color(0xff0b1020),
  colorSurfaceBackground: Color(0xff111827),
  colorBorderNeutralSubtle: Color(0xff374151),
  colorActionSuccess: Color(0xff4ade80),
  colorActionSuccessBackground: Color(0xff052e16),
  colorActionSuccessBorder: Color(0xff14532d),
  colorActionError: Color(0xfff87171),
  colorActionErrorBackground: Color(0xff450a0a),
  colorActionErrorBorder: Color(0xff7f1d1d),
  colorTextBaseline: Color(0xfff3f4f6),
  colorTextSecondary: Color(0xffd1d5db),
  colorTextMuted: Color(0xff9ca3af),
  colorMuted: Color(0xff1f2937),
  colorRatingAgainBackground: Color(0xff450a0a),
  colorRatingAgainText: Color(0xffff8a80),
  colorRatingAgainBorder: Color(0xff7f1d1d),
  colorRatingAgainHoverBackground: Color(0xff5f1414),
  colorRatingHardBackground: Color(0xff431407),
  colorRatingHardText: Color(0xffffb74d),
  colorRatingHardBorder: Color(0xff7c2d12),
  colorRatingHardHoverBackground: Color(0xff5a1d0a),
  colorRatingGoodBackground: Color(0xff052e16),
  colorRatingGoodText: Color(0xff81c784),
  colorRatingGoodBorder: Color(0xff14532d),
  colorRatingGoodHoverBackground: Color(0xff0b3d1f),
  colorRatingEasyBackground: Color(0xff082f49),
  colorRatingEasyText: Color(0xff64b5f6),
  colorRatingEasyBorder: Color(0xff075985),
  colorRatingEasyHoverBackground: Color(0xff0c4a6e),
  colorTransparent: colorTransparent,
  colorTextOnBrand: colorTextOnBrand,
  colorGoogle: Color(0xFF131314),
  colorGoogleDim: Color(0xFF3A3A3A),
  colorTextOnGoogle: Color(0xFFE3E3E3),
  colorMono: Color(0xFFFFFFFF),
  colorMonoDim: Color(0xFFDADADA),
  colorTextOnMono: Color(0xFF000000),
  textSizeHeaderLarge: textSizeHeaderLarge,
  buttonShadowOffset: buttonShadowOffset,
  modalShadowOffset: modalShadowOffset,
  fontWeightTextBody: fontWeightTextBody,
  fontWeightTextStrong: fontWeightTextStrong,
  fontWeightTextHeavy: fontWeightTextHeavy,
  lineHeightTextBody: lineHeightTextBody,
  lineHeightTextTitle: lineHeightTextTitle,
  lineHeightTextDisplay: lineHeightTextDisplay,
  lineHeightFieldDisplay: lineHeightFieldDisplay,
  lineHeightButton: lineHeightButton,
  letterSpacingTextEyebrow: letterSpacingTextEyebrow,
  radiusSurfaceLg: radiusSurfaceLg,
  radiusSurface: radiusSurface,
  radiusSurfaceSm: radiusSurfaceSm,
  borderWidthDefault: borderWidthDefault,
  spaceScaffoldPadding: spaceScaffoldPadding,
  spaceLayoutPadding: spaceLayoutPadding,
  spaceLayoutGapLg: spaceLayoutGapLg,
  spaceLayoutGapMd: spaceLayoutGapMd,
  spaceLayoutGapSm: spaceLayoutGapSm,
  spaceScaffoldMaxWidth: spaceScaffoldMaxWidth,
  textSizeHeader: textSizeHeader,
  textSizeLabelLarge: textSizeLabelLarge,
  textSizeLabel: textSizeLabel,
  textSizeLabelSmall: textSizeLabelSmall,
  textSizeBodyLarge: textSizeBodyLarge,
  sizeIconMd: sizeIconMd,
  sizeIconLg: sizeIconLg,
  studyCardWidth: studyCardWidth,
  studyCardAspectRatio: studyCardAspectRatio,
  studyCardRadius: studyCardRadius,
  studyCardTextSizeFront: studyCardTextSizeFront,
  studyCardTextSizeBack: studyCardTextSizeBack,
  studyCardTextSizeBackContent: studyCardTextSizeBackContent,
);

final booMondaiDark = ThemeVariant<AppTokens>(
  themePresetId: 'boomondai',
  brightness: ThemeVariantBrightness.dark,
  themeData: buildAppThemeData(defaultDark, Brightness.dark),
  tokens: defaultDark,
);
