import 'package:boo_mondai/core/theme/app_tokens.shared.dart';
import 'package:boo_mondai/lib.barrel.dart'
    show
        AppTokens,
        fontFamily,
        radiusSurface,
        radiusSurfaceLg,
        radiusSurfaceSm,
        buttonShadowOffset,
        modalShadowOffset,
        borderWidthDefault,
        spaceScaffoldPadding,
        spaceLayoutPadding,
        spaceLayoutGapSm,
        spaceLayoutGapLg,
        spaceLayoutGapMd,
        spaceScaffoldMaxWidth,
        textSizeHeader,
        textSizeLabelLarge,
        textSizeLabel,
        textSizeLabelSmall,
        textSizeBodyLarge,
        studyCardTextSizeFront,
        studyCardTextSizeBack,
        studyCardTextSizeBackContent,
        fontWeightTextBody,
        fontWeightTextStrong,
        fontWeightTextHeavy,
        lineHeightTextBody,
        lineHeightTextTitle,
        lineHeightTextDisplay,
        lineHeightFieldDisplay,
        lineHeightButton,
        letterSpacingTextEyebrow,
        sizeIconMd,
        sizeIconLg,
        colorTransparent,
        colorTextOnBrand,
        studyCardAspectRatio,
        studyCardWidth,
        studyCardRadius,
        buildAppThemeData;
import 'package:flutter/material.dart' show Color, Brightness;
import 'package:theme_variants/theme_variants.dart'
    show ThemeVariant, ThemeVariantBrightness;

final AppTokens defaultLight = AppTokens(
  name: 'BooMondai Light',
  fontFamily: fontFamily,
  colorPrimaryBright: Color(0xffc7d2fe),
  colorPrimaryDim: Color(0xff3f498a),
  colorPrimarySoft: Color(0xffeef2ff),
  colorStreak: Color(0xfff97316),
  colorStreakDim: Color(0xffc2410c),
  colorPageBackground: Color(0xfff8f9fa),
  colorSurfaceBackground: Color(0xffffffff),
  colorBorderNeutralSubtle: Color(0xffe5e7eb),
  colorActionSuccess: Color(0xff22c55e),
  colorActionSuccessBackground: Color(0xfff0fdf4),
  colorActionSuccessBorder: Color(0xffbbf7d0),
  colorActionError: Color(0xffef4444),
  colorActionErrorBackground: Color(0xfffef2f2),
  colorActionErrorBorder: Color(0xfffecaca),
  colorTextBaseline: Color(0xff111827),
  colorTextSecondary: Color(0xff6b7280),
  colorTextMuted: Color(0xff9ca3af),
  colorMuted: Color(0xfff3f4f6),
  colorRatingAgainBackground: Color(0xfffef2f2),
  colorRatingAgainText: Color(0xfff44336),
  colorRatingAgainBorder: Color(0xfffecaca),
  colorRatingAgainHoverBackground: Color(0xfffee2e2),
  colorRatingHardBackground: Color(0xfffff7ed),
  colorRatingHardText: Color(0xffff9800),
  colorRatingHardBorder: Color(0xfffed7aa),
  colorRatingHardHoverBackground: Color(0xffffedd5),
  colorRatingGoodBackground: Color(0xfff0fdf4),
  colorRatingGoodText: Color(0xff4caf50),
  colorRatingGoodBorder: Color(0xffbbf7d0),
  colorRatingGoodHoverBackground: Color(0xffdcfce7),
  colorRatingEasyBackground: Color(0xffeff6ff),
  colorRatingEasyText: Color(0xff2196f3),
  colorRatingEasyBorder: Color(0xffbfdbfe),
  colorRatingEasyHoverBackground: Color(0xffdbeafe),
  colorTransparent: colorTransparent,
  colorTextOnBrand: colorTextOnBrand,
  colorGoogle: Color(0xFFFFFFFF),
  colorGoogleDim: Color(0xFFDADADA),
  colorTextOnGoogle: Color(0xFF1F1F1F),
  colorMono: Color(0xFF000000),
  colorMonoDim: Color(0xFF3A3A3A),
  colorTextOnMono: Color(0xFFFFFFFF),
  textSizeHeaderLarge: textSizeHeaderLarge,
  buttonShadowOffset: buttonShadowOffset,
  modalShadowOffset: modalShadowOffset,
  fontWeightTextBody: fontWeightTextBody,
  fontWeightTextStrong: fontWeightTextStrong,
  fontWeightTextHeavy: fontWeightTextHeavy,
  lineHeightTextBody: lineHeightTextBody,
  lineHeightTextTitle: lineHeightTextTitle,
  lineHeightTextDisplay: lineHeightTextDisplay,
  lineHeightFieldDisplay: lineHeightFieldDisplay,
  lineHeightButton: lineHeightButton,
  letterSpacingTextEyebrow: letterSpacingTextEyebrow,
  radiusSurfaceLg: radiusSurfaceLg,
  radiusSurface: radiusSurface,
  radiusSurfaceSm: radiusSurfaceSm,
  borderWidthDefault: borderWidthDefault,
  spaceScaffoldPadding: spaceScaffoldPadding,
  spaceLayoutPadding: spaceLayoutPadding,
  spaceLayoutGapLg: spaceLayoutGapLg,
  spaceLayoutGapMd: spaceLayoutGapMd,
  spaceLayoutGapSm: spaceLayoutGapSm,
  spaceScaffoldMaxWidth: spaceScaffoldMaxWidth,
  textSizeHeader: textSizeHeader,
  textSizeLabelLarge: textSizeLabelLarge,
  textSizeLabel: textSizeLabel,
  textSizeLabelSmall: textSizeLabelSmall,
  textSizeBodyLarge: textSizeBodyLarge,
  sizeIconMd: sizeIconMd,
  sizeIconLg: sizeIconLg,
  studyCardWidth: studyCardWidth,
  studyCardAspectRatio: studyCardAspectRatio,
  studyCardRadius: studyCardRadius,
  studyCardTextSizeFront: studyCardTextSizeFront,
  studyCardTextSizeBack: studyCardTextSizeBack,
  studyCardTextSizeBackContent: studyCardTextSizeBackContent,
);

final booMondaiLight = ThemeVariant<AppTokens>(
  themePresetId: 'boomondai',
  brightness: ThemeVariantBrightness.light,
  themeData: buildAppThemeData(defaultLight, Brightness.light),
  tokens: defaultLight,
);
