import 'package:boo_mondai/lib.barrel.dart'
    show
        AppTokens,
        fontFamily,
        radiusContainerLarge,
        radius2xl,
        radius3xl,
        surfaceShadowOffset,
        modalShadowOffset,
        borderWidthDefault,
        spacePanelPadding,
        spacePanelGapSm,
        spacePanelGapLg,
        spacePanelGapMd,
        textSizeHeader,
        textSizeLabelLarge,
        textSizeLabel,
        textSizeLabelSmall,
        textSizeBodyLarge,
        textSizeCardFront,
        textSizeCardBackFront,
        textSizeCardBackContent,
        fontWeightTextBody,
        fontWeightTextStrong,
        fontWeightTextHeavy,
        lineHeightTextBody,
        lineHeightTextTitle,
        lineHeightTextDisplay,
        lineHeightFieldDisplay,
        lineHeightTactile,
        letterSpacingTextEyebrow,
        sizeIconMd,
        sizeIconLg,
        colorTransparent,
        colorTextOnBrand,
        cardAspectRatio,
        buildAppThemeData;
import 'package:flutter/material.dart' show Color, Brightness;
import 'package:theme_variants/theme_variants.dart'
    show ThemeVariant, ThemeVariantBrightness;

final AppTokens defaultLight = AppTokens(
  name: 'BooMondai Light',
  fontFamily: fontFamily,
  primary: Color(0xff6366f1),
  primaryDim: Color(0xff3f498a),
  primaryBright: Color(0xffc7d2fe),
  primarySoft: Color(0xffeef2ff),
  streak: Color(0xfff97316),
  streakDim: Color(0xffc2410c),
  backgroundPage: Color(0xfff8f9fa),
  backgroundSurface: Color(0xffffffff),
  borderNeutralSubtle: Color(0xffe5e7eb),
  actionSuccess: Color(0xff22c55e),
  actionSuccessBackground: Color(0xfff0fdf4),
  actionSuccessBorder: Color(0xffbbf7d0),
  actionError: Color(0xffef4444),
  actionErrorBackground: Color(0xfffef2f2),
  actionErrorBorder: Color(0xfffecaca),
  textPrimary: Color(0xff111827),
  textSecondary: Color(0xff6b7280),
  textMuted: Color(0xff9ca3af),
  softGray: Color(0xfff3f4f6),
  greenSoft: Color(0xfff0fdf4),
  ratingAgainBackground: Color(0xfffef2f2),
  ratingAgainText: Color(0xfff44336),
  ratingAgainBorder: Color(0xfffecaca),
  ratingAgainHoverBackground: Color(0xfffee2e2),
  ratingHardBackground: Color(0xfffff7ed),
  ratingHardText: Color(0xffff9800),
  ratingHardBorder: Color(0xfffed7aa),
  ratingHardHoverBackground: Color(0xffffedd5),
  ratingGoodBackground: Color(0xfff0fdf4),
  ratingGoodText: Color(0xff4caf50),
  ratingGoodBorder: Color(0xffbbf7d0),
  ratingGoodHoverBackground: Color(0xffdcfce7),
  ratingEasyBackground: Color(0xffeff6ff),
  ratingEasyText: Color(0xff2196f3),
  ratingEasyBorder: Color(0xffbfdbfe),
  ratingEasyHoverBackground: Color(0xffdbeafe),
  radiusContainerLarge: radiusContainerLarge,
  radius2xl: radius2xl,
  radius3xl: radius3xl,
  surfaceShadowOffset: surfaceShadowOffset,
  modalShadowOffset: modalShadowOffset,
  borderWidthDefault: borderWidthDefault,
  spacePanelPadding: spacePanelPadding,
  spacePanelPaddingSm: spacePanelGapSm,
  spacePanelGapLg: spacePanelGapLg,
  spacePanelGapMd: spacePanelGapMd,
  spacePanelGapSm: spacePanelGapSm,
  textSizeHeader: textSizeHeader,
  textSizeLabelLarge: textSizeLabelLarge,
  textSizeLabel: textSizeLabel,
  textSizeLabelSmall: textSizeLabelSmall,
  textSizeBodyLarge: textSizeBodyLarge,
  textSizeCardFront: textSizeCardFront,
  textSizeCardBackFront: textSizeCardBackFront,
  textSizeCardBackContent: textSizeCardBackContent,
  fontWeightTextBody: fontWeightTextBody,
  fontWeightTextStrong: fontWeightTextStrong,
  fontWeightTextHeavy: fontWeightTextHeavy,
  lineHeightTextBody: lineHeightTextBody,
  lineHeightTextTitle: lineHeightTextTitle,
  lineHeightTextDisplay: lineHeightTextDisplay,
  lineHeightFieldDisplay: lineHeightFieldDisplay,
  lineHeightTactile: lineHeightTactile,
  letterSpacingTextEyebrow: letterSpacingTextEyebrow,
  sizeIconMd: sizeIconMd,
  sizeIconLg: sizeIconLg,
  colorTransparent: colorTransparent,
  colorTextOnBrand: colorTextOnBrand,
  cardAspectRatio: cardAspectRatio,
);

final booMondaiLight = ThemeVariant<AppTokens>(
  themePresetId: 'boomondai',
  brightness: ThemeVariantBrightness.light,
  themeData: buildAppThemeData(defaultLight, Brightness.light),
  tokens: defaultLight,
);
